"""empty message

Revision ID: 94a7285d12be
Revises: 39b19d748881
Create Date: 2021-01-06 08:40:10.737430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a7285d12be'
down_revision = '39b19d748881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hs_code', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('chapter', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tariff')
    # ### end Alembic commands ###
