"""empty message

Revision ID: cf1b85b3d7a6
Revises: e2bf4e1f3d00
Create Date: 2021-01-15 12:44:06.847162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf1b85b3d7a6'
down_revision = 'e2bf4e1f3d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regions')
    op.drop_table('tariffs')
    op.drop_table('sections')
    op.drop_table('countries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name='countries_region_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='countries_pkey')
    )
    op.create_table('sections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sections_pkey')
    )
    op.create_table('tariffs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hs_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('chapter', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['tariffs.id'], name='tariffs_parent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tariffs_pkey')
    )
    op.create_table('regions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='regions_pkey')
    )
    # ### end Alembic commands ###
